insert into public.lessons (module_id, title, type, video_url, content_text, duration_seconds, order_index, is_free_preview)
select m.id, v.title, v.ltype::lesson_type, v.url, v.txt, v.dur, v.ord, v.free
from public.course_modules m join public.courses c on c.id = m.course_id,
(values
(0, 'Jumping Right Into the World of Artificial Intelligence', 'video', 'https://drive.google.com/file/d/1XZ5-PaaolxA2FJ_ywjZWIOfJ6mt-vDEM/preview', null, 600, 0, true),
(0, 'Setting Up Ollama on Mac & Windows for Local Testing', 'video', 'https://drive.google.com/file/d/1LUmIjf9rhpA_Y63IRtaIhe0UnitJT37l/preview', null, 600, 1, false),
(0, 'Build Your First AI Application: English Tutor Using Ollama', 'video', 'https://drive.google.com/file/d/1Qclkmz8f7iZwMCbgqMa2buBSami_FwjY/preview', null, 600, 2, false),
(0, 'Explore NotebookLM from Google', 'video', 'https://drive.google.com/file/d/1rVYyTqY_HqU2P-9uAbszSSs6qJHfoyzA/preview', null, 600, 3, false),
(0, 'Course Roadmap', 'video', 'https://drive.google.com/file/d/1H_TV8lsx3E8I53yQtX0FqS1Qb1_x46va/preview', null, 600, 4, false),
(0, 'Know Your Instructor (optional)', 'video', 'https://drive.google.com/file/d/19vSXytkmGVUt0dTCVOcPwu8TLQd8oSAR/preview', null, 600, 5, false),
(0, 'A Look at Widely Used Closed and Open Source Models', 'video', 'https://drive.google.com/file/d/1-dySTYNlZ3cL0UaCX6kXIdcRXCjUbnjF/preview', null, 600, 6, false),
(1, 'Generative AI vs Traditional AI', 'video', 'https://drive.google.com/file/d/13AdrHgNOZWVT10esto69sjq8bldv-XXO/preview', null, 600, 0, false),
(1, 'What Are Large Language Models (LLMs)?', 'video', 'https://drive.google.com/file/d/1I43a36gcwEwaGBJ8DqY68DOS_m1TgZrM/preview', null, 600, 1, false),
(1, 'How an LLM Works', 'video', 'https://drive.google.com/file/d/1OWfxDEZg2uc5-0q4LxzeuEskbXDzKDDO/preview', null, 600, 2, false),
(1, 'What Are Tokens?', 'video', 'https://drive.google.com/file/d/1T5qr_d-Q1VgolPQTBEbtm0zpJEDclMps/preview', null, 600, 3, false),
(1, 'AI Jargon: Inference, Context Window, Hallucinations, RAG', 'video', 'https://drive.google.com/file/d/12nL91O9ohCMAEO5CZTRviatSr_T8hwWi/preview', null, 600, 4, false),
(2, 'Why Do We Need to Engineer a Prompt?', 'video', 'https://drive.google.com/file/d/1RD_4F9WBpdgYXSXk1xCo8MZ3LVwY3PvL/preview', null, 600, 0, false),
(2, 'Role of Temperature, Top-K and Top-P in Sampling Output', 'video', 'https://drive.google.com/file/d/1NMKKlVyRBHofWAsWDyphyVB08TxE2Zv2/preview', null, 600, 1, false),
(2, 'Components of a Prompt', 'video', 'https://drive.google.com/file/d/1DgLF36-O6-DBwbvJX-UQj9t5j3vLd8XA/preview', null, 600, 2, false),
(2, 'Zero-Shot Prompting', 'video', 'https://drive.google.com/file/d/1WJuK6z32iDE1ZBlpn4kGf3Q-QBSdlAeA/preview', null, 600, 3, false),
(2, 'One-Shot and Few-Shot Prompting', 'video', 'https://drive.google.com/file/d/1tBuvZPpwIkx3_lcB1voyGOdlP6AH00mO/preview', null, 600, 4, false),
(2, 'Chain-of-Thought (CoT) Prompting', 'video', 'https://drive.google.com/file/d/14MyUds2PpPlfowJVE-NK0GYdJRNfKyjh/preview', null, 600, 5, false),
(2, 'ReAct (Reason and Act) Prompting', 'video', 'https://drive.google.com/file/d/1L53qofDJcOo6KIQsgbzvr54rGF7l3Fxq/preview', null, 600, 6, false),
(2, 'System, Contextual and Role Prompting', 'video', 'https://drive.google.com/file/d/1LJeipXz9kRzKdwTDfAsFWL4g8Hua8YO5/preview', null, 600, 7, false),
(3, 'What Is an AI Agent?', 'text', null, 'Lesson notes and transcript are provided with this session.', 120, 0, false),
(3, 'Components of an AI Agent', 'text', null, 'Lesson notes and transcript are provided with this session.', 120, 1, false),
(3, 'AWS Bedrock Agent — A Serverless Service', 'text', null, 'Lesson notes and transcript are provided with this session.', 120, 2, false),
(3, 'Understanding Our AIOps Agent Architecture and Prerequisites', 'text', null, 'Lesson notes and transcript are provided with this session.', 120, 3, false),
(3, 'Set Up the AWS CLI and AWS Credentials', 'text', null, 'Downloadable resources for this lesson: https://drive.google.com/drive/folders/1wd36OzDToP-D_BasOyNOdQJsi6iwuaiJ', 120, 4, false),
(3, 'Create an AIOps AI Agent in AWS Bedrock', 'text', null, 'Downloadable resources for this lesson: https://drive.google.com/drive/folders/1rNzVcMmLFTKvkdkbfD72u25C42jskCjr', 120, 5, false),
(3, 'Responsible AI Principles', 'text', null, 'Lesson notes and transcript are provided with this session.', 120, 6, false),
(4, 'Understanding Retrieval-Augmented Generation (RAG)', 'video', 'https://drive.google.com/file/d/1KCbMbpxfWPskFbcanXsiWCWvptO4l3K9/preview', null, 600, 0, false),
(4, 'Front Desk Agent Without RAG — Understanding the Problem', 'video', 'https://drive.google.com/file/d/1GDLAiOMP5UbQE7bc2i9BryM12Dhm5HX2/preview', null, 600, 1, false),
(4, 'Implementing a RAG-Based Front Desk Agent Using Langflow', 'video', 'https://drive.google.com/file/d/1cn9IjdyHIQqe4NHwnXZmYFKc-XYKqK5x/preview', null, 600, 2, false),
(4, 'Traditional RAG vs Agentic RAG', 'video', 'https://drive.google.com/file/d/1f8gphfvPATt6KwAO_3H4cfSh9JmhOUiW/preview', null, 600, 3, false),
(4, 'Implementing Agentic RAG', 'video', 'https://drive.google.com/file/d/1kn4n_PUErvXxLU7dJImFIBthQ9H-bSDY/preview', null, 600, 4, false),
(5, 'What Is MCP — The Universal Connector for AI', 'video', 'https://drive.google.com/file/d/1HudzePXMY7PXjHO_Xv_8bOTSp0lKpmAE/preview', null, 600, 0, false),
(5, 'Get a Taste of the Docker MCP Server', 'video', 'https://drive.google.com/file/d/11NLG3KcYgJ-w8H3ubWVB0ITNXetp2Mo0/preview', null, 600, 1, false),
(5, 'Basic MCP Architecture', 'video', 'https://drive.google.com/file/d/1Djuzv076xPj0iyjsiV_qfWwLjRTCvT6I/preview', null, 600, 2, false),
(5, 'Project: Build Your Own MCP Server to Manage Google Calendar', 'video', 'https://drive.google.com/file/d/1AEppO0zk5O1FLhyXyk9OCWmsmHirvUia/preview', null, 600, 3, false),
(6, 'What Is Claude?', 'video', 'https://drive.google.com/file/d/1sm6a6E329KW0bRaiXJ6LsLxK_xYsrTTW/preview', null, 600, 0, false),
(6, 'Installing Claude Desktop', 'video', 'https://drive.google.com/file/d/1LeKj0ZxUlui1MHQrw0_mIKppvlGWYUe4/preview', null, 600, 1, false),
(6, 'Claude Features — Not Just a Chatbot', 'video', 'https://drive.google.com/file/d/1uDYoaWDOjvWktt8vKrZt2uLoRz7mE9ye/preview', null, 600, 2, false),
(6, 'The Claude Model Family', 'video', 'https://drive.google.com/file/d/1y5IGuoOOMkFtJX_PegRIUtlzfOIuym1N/preview', null, 600, 3, false),
(6, 'What Is Claude Code?', 'text', null, 'Lesson notes and transcript are provided with this session.', 120, 4, false),
(6, 'Build a Real App Using Claude Code', 'text', null, 'Lesson notes and transcript are provided with this session.', 120, 5, false),
(6, 'Overview of Claude Skills', 'text', null, 'Lesson notes and transcript are provided with this session.', 120, 6, false),
(6, 'Using Claude Skills', 'text', null, 'Lesson notes and transcript are provided with this session.', 120, 7, false),
(6, 'Creating a New Claude Skill', 'text', null, 'Lesson notes and transcript are provided with this session.', 120, 8, false),
(7, 'Wrap-Up', 'video', 'https://drive.google.com/file/d/1qg71OAGmv_0Pybvf7HYp9MhJhDm7Gp18/preview', null, 600, 0, false)
) as v(midx, title, ltype, url, txt, dur, ord, free)
where c.slug='generative-ai-llms-agents-mcp' and m.order_index = v.midx
and not exists (select 1 from public.lessons l where l.module_id = m.id and l.order_index = v.ord);