-- Seed: coding problems for the Full Stack course, inserted as DRAFTS (publish them in Admin → Coding problems).
-- Every problem was verified against LeetCode / HackerRank public APIs on 2026-10-02 (exact title, difficulty, free).
-- Idempotent: re-running skips existing (course, url) rows. Skipped silently if the course or a module is missing.
INSERT INTO public.coding_problems (course_id, module_id, title, platform, url, difficulty, order_index, is_published)
SELECT c.id, m.id, v.title, v.platform, v.url, v.difficulty, v.ord, false
FROM (VALUES
  ('JavaScript', 'Create Hello World Function', 'leetcode', 'https://leetcode.com/problems/create-hello-world-function/', 'easy', 1),
  ('JavaScript', 'Counter', 'leetcode', 'https://leetcode.com/problems/counter/', 'easy', 2),
  ('JavaScript', 'To Be Or Not To Be', 'leetcode', 'https://leetcode.com/problems/to-be-or-not-to-be/', 'easy', 3),
  ('JavaScript', 'Counter II', 'leetcode', 'https://leetcode.com/problems/counter-ii/', 'easy', 4),
  ('JavaScript', 'Apply Transform Over Each Element in Array', 'leetcode', 'https://leetcode.com/problems/apply-transform-over-each-element-in-array/', 'easy', 5),
  ('JavaScript', 'Filter Elements from Array', 'leetcode', 'https://leetcode.com/problems/filter-elements-from-array/', 'easy', 6),
  ('JavaScript', 'Array Reduce Transformation', 'leetcode', 'https://leetcode.com/problems/array-reduce-transformation/', 'easy', 7),
  ('JavaScript', 'Function Composition', 'leetcode', 'https://leetcode.com/problems/function-composition/', 'easy', 8),
  ('JavaScript', 'Return Length of Arguments Passed', 'leetcode', 'https://leetcode.com/problems/return-length-of-arguments-passed/', 'easy', 9),
  ('JavaScript', 'Allow One Function Call', 'leetcode', 'https://leetcode.com/problems/allow-one-function-call/', 'easy', 10),
  ('JavaScript', 'Memoize', 'leetcode', 'https://leetcode.com/problems/memoize/', 'medium', 11),
  ('JavaScript', 'Chunk Array', 'leetcode', 'https://leetcode.com/problems/chunk-array/', 'easy', 12),
  ('JavaScript', 'Array Prototype Last', 'leetcode', 'https://leetcode.com/problems/array-prototype-last/', 'easy', 13),
  ('JavaScript', 'Group By', 'leetcode', 'https://leetcode.com/problems/group-by/', 'medium', 14),
  ('JavaScript', 'Sort By', 'leetcode', 'https://leetcode.com/problems/sort-by/', 'easy', 15),
  ('JavaScript', 'Join Two Arrays by ID', 'leetcode', 'https://leetcode.com/problems/join-two-arrays-by-id/', 'medium', 16),
  ('JavaScript', 'Flatten Deeply Nested Array', 'leetcode', 'https://leetcode.com/problems/flatten-deeply-nested-array/', 'medium', 17),
  ('JavaScript', 'Compact Object', 'leetcode', 'https://leetcode.com/problems/compact-object/', 'medium', 18),
  ('JavaScript', 'Is Object Empty', 'leetcode', 'https://leetcode.com/problems/is-object-empty/', 'easy', 19),
  ('Advanced JavaScripts', 'Sleep', 'leetcode', 'https://leetcode.com/problems/sleep/', 'easy', 1),
  ('Advanced JavaScripts', 'Timeout Cancellation', 'leetcode', 'https://leetcode.com/problems/timeout-cancellation/', 'easy', 2),
  ('Advanced JavaScripts', 'Interval Cancellation', 'leetcode', 'https://leetcode.com/problems/interval-cancellation/', 'easy', 3),
  ('Advanced JavaScripts', 'Promise Time Limit', 'leetcode', 'https://leetcode.com/problems/promise-time-limit/', 'medium', 4),
  ('Advanced JavaScripts', 'Cache With Time Limit', 'leetcode', 'https://leetcode.com/problems/cache-with-time-limit/', 'medium', 5),
  ('Advanced JavaScripts', 'Debounce', 'leetcode', 'https://leetcode.com/problems/debounce/', 'medium', 6),
  ('Advanced JavaScripts', 'Execute Asynchronous Functions in Parallel', 'leetcode', 'https://leetcode.com/problems/execute-asynchronous-functions-in-parallel/', 'medium', 7),
  ('Advanced JavaScripts', 'Add Two Promises', 'leetcode', 'https://leetcode.com/problems/add-two-promises/', 'easy', 8),
  ('Advanced JavaScripts', 'Event Emitter', 'leetcode', 'https://leetcode.com/problems/event-emitter/', 'medium', 9),
  ('Advanced JavaScripts', 'Array Wrapper', 'leetcode', 'https://leetcode.com/problems/array-wrapper/', 'easy', 10),
  ('Advanced JavaScripts', 'Calculator with Method Chaining', 'leetcode', 'https://leetcode.com/problems/calculator-with-method-chaining/', 'easy', 11),
  ('Fundamentals of Data Science', 'Day 0: Mean, Median, and Mode', 'hackerrank', 'https://www.hackerrank.com/challenges/s10-basic-statistics/problem', 'easy', 1),
  ('Fundamentals of Data Science', 'Day 0: Weighted Mean', 'hackerrank', 'https://www.hackerrank.com/challenges/s10-weighted-mean/problem', 'easy', 2),
  ('Fundamentals of Data Science', 'Day 1: Quartiles', 'hackerrank', 'https://www.hackerrank.com/challenges/s10-quartiles/problem', 'easy', 3),
  ('Fundamentals of Data Science', 'Day 1: Standard Deviation', 'hackerrank', 'https://www.hackerrank.com/challenges/s10-standard-deviation/problem', 'easy', 4),
  ('Python The Most Powerful Language', 'Say "Hello, World!" With Python', 'hackerrank', 'https://www.hackerrank.com/challenges/py-hello-world/problem', 'easy', 1),
  ('Python The Most Powerful Language', 'Python If-Else', 'hackerrank', 'https://www.hackerrank.com/challenges/py-if-else/problem', 'easy', 2),
  ('Python The Most Powerful Language', 'Arithmetic Operators', 'hackerrank', 'https://www.hackerrank.com/challenges/python-arithmetic-operators/problem', 'easy', 3),
  ('Python The Most Powerful Language', 'Python: Division', 'hackerrank', 'https://www.hackerrank.com/challenges/python-division/problem', 'easy', 4),
  ('Python The Most Powerful Language', 'Loops', 'hackerrank', 'https://www.hackerrank.com/challenges/python-loops/problem', 'easy', 5),
  ('Python The Most Powerful Language', 'Write a function', 'hackerrank', 'https://www.hackerrank.com/challenges/write-a-function/problem', 'medium', 6),
  ('Python The Most Powerful Language', 'Print Function', 'hackerrank', 'https://www.hackerrank.com/challenges/python-print/problem', 'easy', 7),
  ('Python The Most Powerful Language', 'List Comprehensions', 'hackerrank', 'https://www.hackerrank.com/challenges/list-comprehensions/problem', 'easy', 8),
  ('Python The Most Powerful Language', 'Find the Runner-Up Score!  ', 'hackerrank', 'https://www.hackerrank.com/challenges/find-second-maximum-number-in-a-list/problem', 'easy', 9),
  ('Python The Most Powerful Language', 'Nested Lists', 'hackerrank', 'https://www.hackerrank.com/challenges/nested-list/problem', 'easy', 10),
  ('Python The Most Powerful Language', 'Finding the percentage', 'hackerrank', 'https://www.hackerrank.com/challenges/finding-the-percentage/problem', 'easy', 11),
  ('Python The Most Powerful Language', 'Lists', 'hackerrank', 'https://www.hackerrank.com/challenges/python-lists/problem', 'easy', 12),
  ('Python The Most Powerful Language', 'Tuples ', 'hackerrank', 'https://www.hackerrank.com/challenges/python-tuples/problem', 'easy', 13),
  ('Python The Most Powerful Language', 'sWAP cASE', 'hackerrank', 'https://www.hackerrank.com/challenges/swap-case/problem', 'easy', 14),
  ('Python The Most Powerful Language', 'String Split and Join', 'hackerrank', 'https://www.hackerrank.com/challenges/python-string-split-and-join/problem', 'easy', 15),
  ('Python The Most Powerful Language', 'What''s Your Name?', 'hackerrank', 'https://www.hackerrank.com/challenges/whats-your-name/problem', 'easy', 16),
  ('Python The Most Powerful Language', 'Mutations', 'hackerrank', 'https://www.hackerrank.com/challenges/python-mutations/problem', 'easy', 17),
  ('Python The Most Powerful Language', 'Find a string', 'hackerrank', 'https://www.hackerrank.com/challenges/find-a-string/problem', 'easy', 18),
  ('Python The Most Powerful Language', 'String Validators', 'hackerrank', 'https://www.hackerrank.com/challenges/string-validators/problem', 'easy', 19),
  ('Python The Most Powerful Language', 'Two Sum', 'leetcode', 'https://leetcode.com/problems/two-sum/', 'easy', 20),
  ('Python The Most Powerful Language', 'Valid Parentheses', 'leetcode', 'https://leetcode.com/problems/valid-parentheses/', 'easy', 21),
  ('Python The Most Powerful Language', 'Reverse String', 'leetcode', 'https://leetcode.com/problems/reverse-string/', 'easy', 22),
  ('Python The Most Powerful Language', 'Fizz Buzz', 'leetcode', 'https://leetcode.com/problems/fizz-buzz/', 'easy', 23),
  ('Python The Most Powerful Language', 'Palindrome Number', 'leetcode', 'https://leetcode.com/problems/palindrome-number/', 'easy', 24),
  ('Python The Most Powerful Language', 'Merge Two Sorted Lists', 'leetcode', 'https://leetcode.com/problems/merge-two-sorted-lists/', 'easy', 25)
) AS v(module_title, title, platform, url, difficulty, ord)
JOIN public.courses c ON c.slug = 'full-stack-web-developer-with-ai-and-ml-integration'
LEFT JOIN public.course_modules m ON m.course_id = c.id AND m.title = v.module_title
ON CONFLICT (course_id, url) DO NOTHING;
