INSERT INTO public.lessons (module_id, title, type, video_url, content_text, duration_seconds, order_index, is_free_preview)
SELECT m.id, l.title,
  (CASE WHEN l.k = 'v' THEN 'video' ELSE 'text' END)::public.lesson_type,
  CASE WHEN l.k = 'v' THEN 'https://drive.google.com/file/d/' || l.fid || '/preview' END,
  CASE WHEN l.k = 't' THEN 'Source file for this lesson.' || chr(10) || chr(10) || 'Open or download: https://drive.google.com/file/d/' || l.fid || '/view'
       WHEN l.k = 'f' THEN l.extra || chr(10) || chr(10) || 'Open the folder: https://drive.google.com/drive/folders/' || l.fid END,
  CASE WHEN l.k = 'v' THEN 600 ELSE 120 END,
  l.li, false
FROM (VALUES
(18,0,'v','Section Introduction','1-nOHOHIl8cySwoxLu4mRiWAQ5DFi6uTv',NULL),
(18,1,'v','Creating the Django Project','1dBE-ev13TY7TqVFgz_o2YZOX20uAScOi',NULL),
(18,2,'v','Connecting Multiple Pages in Django','1XG9s_l7YdFd1c1wzBGxdPWC6sVetEmo9',NULL),
(18,3,'v','How to Import a Model in Django — Part 1','1X9nOJP1YP47zfpasTj9CioW1sGaHXUp2',NULL),
(18,4,'v','How to Import a Model in Django — Part 2','1tYGsH-UGcF3QMj2tH4mE58kf3F7Upv4w',NULL),
(18,5,'v','Integrating a Machine Learning Model with Django','1VYlS3waLtDy3iH9byt7jQm7zYuJpeMyq',NULL),
(18,6,'t','Cleaned Project Files','1c8Aiax7EorZ9xysILwz4jhLbpYMURPPn',NULL),
(18,7,'v','Using Amazon Web Services for an ML Model','15HrUFgE4XMug1lqYMo4mL1QuPemEDwYm',NULL),
(18,8,'t','Steps Needed for the Upcoming Lessons','1TYCSpvP8ns4FZVqKDPAzb_sgb0AxJIj_',NULL),
(18,9,'v','Connecting the AWS Machine with Your Local Machine','1YuR4h-nlXtyKeOy0XKDneQtBWzxUddDS',NULL),
(18,10,'v','Moving Our Web App to Git and AWS','1CKdEcV5xn8T0zhbok8iyp4XTLuWU79RN',NULL),
(18,11,'t','Steps So You Do Not Miss Anything','1IAAWA0-lVBBaYl6LnqS1n0zLEDVwjg2n',NULL),
(18,12,'v','Making Our Machine Learning App Live on the Internet','1GSSgYvFI2v8erf4fQt5LxuklLoi4aVRh',NULL),
(18,13,'v','Validating Our Machine Learning Model','1Jnja7UNv5HNQ-A1PKNp7kdq3UpXBTzJr',NULL),
(18,14,'v','Installing Gunicorn','1DEFyUrt292-DOdydxM5mBFbJMMC81cdT',NULL),
(18,15,'v','Creating the .sock File and Nginx — Part 1','1_5iiCqkovezGjFPAHqdXsz736rbRWYdM',NULL),
(18,16,'v','Creating the .sock File and Nginx — Part 2','1GMwvrFYaYBdLfCjpHyArxwv3AO1S7vT6',NULL),
(18,17,'t','Steps Needed for These Lectures','1prrSz3MqejI_yMltCMfzDWUIRCY0LJ4Y',NULL),
(18,18,'v','Connecting a Domain Name','1tl5fD-62jrJLKM42F7nzYm9uenxNC3tA',NULL),
(18,19,'v','How to Make Changes in Your Live Web App','1SNSLUJoIpYbhoJ3UeP5DsNo1ssgb6OAS',NULL),
(18,20,'v','Adding CSS and JavaScript Files to the ML App','13FowdZxJH8YUHDiAV2fS9TabO4Ee0xNk',NULL),
(18,21,'t','Steps Needed','1-BrfQxjIItGyyBxmRCONWW17kd_MreBb',NULL),
(19,0,'f','All code and projects so far (resources)','1lTjO0KJIGtqAWcovUDWgb75nOXOWyoQ2','Files: Data_Science.rar, ML_titanic.rar, titanic_project.rar'),
(19,1,'v','Introduction to Neural Networks','1BdpNI2Te60F9Od2L4hOs7Hg_Md-7e20F',NULL),
(19,2,'v','Machine Learning vs Deep Learning','1T-qtWckrBV8bo7WaioLfDlFGJ0lTxifA',NULL),
(19,3,'v','Recap of the Basics: Regression, Loss and Cost','1zf_A2_EyorSXNkgyh14MXbb1D7PTDqPN',NULL),
(19,4,'v','Neural Net Fundamentals','1hbHBZsblDNeHTRCc2nXYPYa4ZNaH_n7V',NULL),
(19,5,'v','Neural Nets with Multiple Inputs','1kwj22CNjwD08S5-t0m3QE7BldPdOXucC',NULL),
(19,6,'v','Bias and Variance: b and w','1ChSGXG78LDFTrN0aGub7eL8YgjNevk5K',NULL),
(19,7,'v','Epochs, Forward and Backward Propagation','1C36zkhd3PoCTGZ2B9-jNu9CPEAOiu6qV',NULL),
(19,8,'v','Bias and Variance','1auaXpAjgkNUcMTHGtjrA3PeZ9BXU2Z-B',NULL),
(19,9,'v','Hyperparameters','1NbOTxwX2W3KNAyu8zq0zTkw0ad8huDgn',NULL),
(19,10,'v','Installing Dependencies for Neural Nets','1w9LFF1XD8d3PXk1wQnJSG_3y_wcMXBcG',NULL),
(19,11,'v','Applying Neural Nets','1AbsaG-2bLvCt3hwbNnYA3ioIscNKMDiv',NULL),
(19,12,'v','Optimising a Neural Network with Hyperparameters','1NqCZuuFJtTvE7Z-a1QLcndTgWkO82urU',NULL),
(19,13,'t','Code: My Neural Network','1FBs5obxu8nVchWpwvFlglOokoH-SC2Pz',NULL),
(19,14,'v','Saving the Model for Reuse in a Web App','1l7Kl8_dvkqegy2fqpp7ZVtnCjq7NDhsC',NULL),
(19,15,'v','How to Get Your Data in the Right Shape','1g4ZWovQ_SWCjTUxNFJbWY3EV2pn3DGgI',NULL),
(19,16,'v','Building a Neural Net Image Classifier — Part 1','1nkpeHa55aMB4iwuXA-aHBNaRnpOOecFs',NULL),
(19,17,'v','Building a Neural Net Image Classifier — Part 2','1szq_AjW0H5oKi91MdHotCkgfNuljBgou',NULL),
(19,18,'t','Code: Image Classifier','1fkQjBvhU5tJtDIQlMXFT6tdDnyCPDMrw',NULL),
(19,19,'t','All code and projects so far','1MaYUfBJNT9cjyWXVBAyiWe5vcBd7jwM8',NULL),
(20,0,'f','Datasets you need (resources)','1bqPBzwgPQH-4kdG2Odhmgqc4BHPK9WXn','Files: humans.zip, robots.zip'),
(20,1,'f','All course data (resources)','1m9gP1bYBxvUD_Nps3jEfvZkpiXcJv0l7','Files: Conv_NN.zip'),
(20,2,'v','Introduction to CNNs','1ZobfPdjW5nr7e2bCWVQ_WrB_WFj3k_EK',NULL),
(20,3,'v','How Filters and Kernels Work','176mF52B1hrc4vTUmiTvvbK7d8KXhJHFy',NULL),
(20,4,'v','Filter Parameters to Improve CNN Accuracy','1yrUfC7l3wNdtmw9BSt7bJwfzuw0XcaR9',NULL),
(20,5,'v','Filter Parameters to Improve CNNs — Part 2','1lhan10QGDZi1McA2AhXaWGZ8FO1cCqda',NULL),
(20,6,'v','Pooling Explained','1IAR2waFUHY1sGfVDS3uCpgNeA6XO-oxV',NULL),
(20,7,'v','Building a Terminator Using a CNN','1fo5RPgK3glvD6vaSAA1V2_Sz4GXQlCkn',NULL),
(20,8,'v','Loading Data for the Terminator CNN','1IDl-M7u3QKrJx4B01vm7n4uc1KBdpiB-',NULL),
(20,9,'t','Code: Used in Upcoming Lessons','1DAiKDpWF0UzSvOYpJCnUtx7wvy15zTWC',NULL),
(20,10,'t','Datasets you need','1elpuWoYia6ujiqFM9sNTzxKnTgceaslq',NULL),
(20,11,'v','Preparing Data for the Terminator CNN','1cSvz4r8o9bpNTqdIc2cnV1BUdqWbjYxr',NULL),
(20,12,'v','Splitting Data into Test and Train','119fa_7FoDQ13jFCYrkUkokunw0q28gld',NULL),
(20,13,'v','How to Improve the Accuracy of a CNN','1YvIppdVDeGyI7Ql8ryhVEvX7FxfUJAyr',NULL),
(20,14,'t','Code: Improving Accuracy','1p92DTcO-YJr_RLnPhiA8evWzGGinc2T7',NULL),
(20,15,'v','Running Predictions on Images in the Dataset','1VnQZFSM8h7pYSmoP3WysjiUd4u8xxvIj',NULL),
(20,16,'v','Running Predictions on Images Outside the Dataset','1-gwY08BLHciLB5Cimo9Q52xxZ3fBTpa8',NULL),
(20,17,'t','Code: Predictions','1xuPY4nECId0yO-8J5bt-EfnD5iU6gGyL',NULL),
(20,18,'t','All course data','14szCuNUrX1aZNgKHHXVoL9ENkCl9rh5B',NULL),
(20,19,'v','Final Note and a Few Words','1TnLaVsHU-BkVylNwMrvmIvUNibr5FlbE',NULL),
(20,20,'v','Models in Django: Create the Project (Optional)','15owjipOxYdD1oljfaIFbz7jbZkHQ2dCg',NULL),
(20,21,'v','What is a Model?','1OBDLTo7XLTfMM-zywm3IN_yl7uXphiTR',NULL),
(20,22,'v','Creating Your First Model','1ZtHYmOYBYan8IdCujBD8ufIL6v_05Z8H',NULL)
) AS l(mi, li, k, title, fid, extra)
JOIN public.course_modules m
  ON m.order_index = l.mi
 AND m.course_id = (SELECT id FROM public.courses WHERE slug = 'full-stack-web-development-with-ai-ml');